package com.bank.bian.atmnetworkmanagement;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: ATM Network Management
 *
 * Business Area:      Sales and Service
 * Business Domain:    Channels
 * Functional Pattern: Operate
 * Asset Type:         ATM Network
 * Control Record:     ATM Network Operating Session
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("ATM Network Management — BIAN Semantic API")
                .description("Service Domain 'ATM Network Management' (Operate pattern) "
                        + "operating on the 'ATM Network Operating Session' control record.")
                .version("0.1.0"));
    }
}
